spring:
  datasource:
    url: jdbc:oracle:thin:@your-database-url:1521:your-service-name
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
